[pytest]

# addopts = default command line options that pytest will automatically use every time tests run
# -v -> verbose mode, shows detailed test execution output in terminal
# -s -> allows print() statements to appear in console during test execution
# --alluredir -> stores test execution results in this folder so Allure can generate reports
addopts = -v -s --alluredir=reports/allure-results

# testpaths tells pytest where to look for test files
# here pytest will only search inside the "tests" folder
testpaths = tests

# python_files defines the naming pattern for test files
# pytest will only execute files starting with "test_"
python_files = test_*.py

# python_classes defines the naming pattern for test classes
# pytest will run classes starting with "Test"
python_classes = Test*

# python_functions defines the naming pattern for test methods/functions
# pytest will execute functions starting with "test_"
python_functions = test_*